= systemd-pixi-generator
:fdt: https://www.freedesktop.org/software/systemd/man/latest/systemd.generator.html

A service generator for pixi global packages.
Generally speaking, 
services are just a specific type of CLI application which is long running,
and does so in the background,
not under the direct control of a login session.

I would expect service packages to provide the metadata 
sufficient to generate their unit-files.

== Systemd Generator

link:{fdt}[man page for the systemd generator]

"Generators are small executables placed in a generators folder.
`systemd(1)` will execute these binaries very early at bootup 
and at configuration reload time —-before unit files are loaded.
Their main purpose is to convert configuration and execution context parameters
that are not native to the service manager into dynamically generated unit files,
symlinks or unit file drop-ins, 
so that they can extend the unit file hierarchy 
the service manager subsequently loads and operates on."

== Installation

This generator is available as a `pixi` package.
[source,bash]
----
pixi global install systemd-pixi-generator
sudo systemd-pixi-generator --mode init
----
The `init` mode creates one symlink for system services and one for user services.

.system services
[source,text]
/run/systemd/system-generators/*
/etc/systemd/system-generators/*
/usr/local/lib/systemd/system-generators/*
/usr/lib/systemd/system-generators/*

.user services
[source,text]
/run/systemd/user-generators/*
/etc/systemd/user-generators/*
/usr/local/lib/systemd/user-generators/*
/usr/lib/systemd/user-generators/*

The presence of these symlinks will induce
the `systemctl daemon-reload`
or `systemctl --user daemon-reload`
to run the generator.

== Behavior

When the generator runs it will generate systemd unit-files according to the following rules:

Examine all the environments in the Pixi global manifest.
For each environment...

Extract information from each package in the environment using
`~/.pixi/envs/mypkg/conda-meta/*.json` metadata.
* description
* name
* extracted_package_dir

The `extracted_package_dir` is searched for a candidate unit-file
e.g., `/etc/systemd/mypkg.service`.
If present, that file becomes be the systemd unit-file (or unit-file template) used.
The generator uses the candidate or the 
link:./src/unit.service.template[default template].
This template is filled out using the metadata previously obtained,
or using information from the corresponding `pixi-global.toml` service element.

=== Pixi Global TOML : Configuration
[source,toml]
----
[envs.nginx]
channels = ["conda-forge"]
dependencies = { nginx = "*" }
exposed = { nginx = "nginx" }
service = { status = "enabled", after = "network.target", 
            exec-start-pre = "$PREFIX/bin/nginx init",
            exec-start = "$PREFIX/bin/nginx -f $CONDA_PREFIX/etc/nginx/nginx.conf" }
----

The unit-file thus produced is placed in the 
link:{fdt}#Output%20directories[appropriate output directory].
"In normal use this is `/run/systemd/generator`
in case of the system generators and 
$XDG_RUNTIME_DIR/systemd/generator in case of the user generators.
Unit files placed in this directory take precedence over vendor unit configuration
but not over native user/administrator unit configuration." 
The presence of this file effectively enables the service.


== Candidate Services Available in `conda-forge`

nginix:: https://github.com/conda-forge/nginx-feedstock
solr:: https://github.com/conda-forge/apache-solr-feedstock
mysql:: https://github.com/conda-forge/mysql-feedstock
mongo:: https://github.com/conda-forge/mongodb-feedstock
redis:: https://github.com/conda-forge/redis-py-feedstock
minio:: https://github.com/conda-forge/minio-feedstock
