# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-rust

name: CI

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always
  CICD_INTERMEDIATES_DIR: "_cicd-intermediates"
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache
  PYTEST_ADDOPTS: "--color=yes"
  CARGO_BUILD_PROFILE: ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
